# Use official Tomcat image with Java 17
FROM tomcat:10-jdk17

# Remove default Tomcat apps (good practice)
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy the WAR file generated by Maven
COPY target/blinkit.war /usr/local/tomcat/webapps/blinkit.war

# Expose Tomcat port
EXPOSE 8080

# Tomcat starts automatically

